name: Sync Bucket

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: "GCP Bucket Sync"
      url: https://assets.tiarasjec.in/
    steps:
      - uses: actions/checkout@v2

      - name: Sync
        uses: patrickwyler/gcs-bucket-sync-action@1.4
        with:
          secrets: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}
          bucket: "tiara-assets"
          exclude: '.*\.md$|\.gitignore$|\.git/.*$|\.github/.*$'
